services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: little_sprouts
    ports:
      - "5432:5432"
    volumes:
      - little_sprouts_db:/var/lib/postgresql/data

volumes:
  little_sprouts_db:
